# This is the configuration file for the ExplodingMobs plugin.
# It contains the configuration for the plugin.
# It is a YAML file, and it is used to configure the plugin.

# 1. For explosion customization.

explosionRadius: 5 # The radius of the explosion.
explosiveMobName: Exploadable Mob # The name of the mob.
explosionEffect: NONE # The effect of the explosion.

# 2. For console customization.

consoleSpawnLocation: 0, 0, 0 # The location of where should the mob spawn in case the command is executed by the console.