name: ExplodingMobs
version: '1.0.1'
main: me.touchie771.explodingMobs.ExplodingMobs
api-version: '1.21'
authors: [ Touchie771 ]
description: A plugin to make any mob exploadable
commands:
  spawnMob:
    description: Spawns an explosive mob.
    usage: /<command> <mobType>
    permission: explodingmobs.spawnMob
    permission-message: You do not have permission to use this command.